# Generated by Django 2.2.13 on 2021-11-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_page',
        ),
    ]
